### PR TITLE
Xcode8 migration

### PR DESCRIPTION
**Pull request by zmeyc**
Xcode 8.0 beta migration

### CODE REVIEW

**Comment by ianpartridge** [comment]
Thanks for the PR!  We'll be planning our migration to `swift3-preview1` soon.

**Comment by kweinmeister** [comment]
@zmeyc Can you please file a [CLA](https://github.com/IBM-Swift/CLA)?

**Comment by zmeyc** [comment]
@kweinmeister Done.

**Comment by irar2** [comment]
Merged manually the enum lower case part.

**Pull request closed without merging**
