### PR TITLE
05/09 Migration

### PR DESCRIPTION
**Pull request by ghost**
@NikitaSullivan @dfirsht 05/09 Migration status:
 [Build Status](https://travis-ci.org/aquarchitect/SwiftyJSON)

**OS X**: 
- [x] Sources compiled
- [x] Tests compiled
- [x] Tests passed

**Linux**:
- [x] Sources compiled
- [ ] Tests compiled
- [ ] Tests passed

### CODE REVIEW

**Comment by dfirsht** [comment]
Hey @aquarchitect, so I've been looking at your changes and it seems we sort of did the same work getting the 0509Migration branch to run on Linux. Can you resolve those conflicts? (It looks like your changes are more precise so you can keep yours). Also I tried running your tests and I got the error: 

```
SwiftyJSON/Tests/SwiftyJSON/RawRepresentableTests.swift:155:16: error: invalid redeclaration of 'allTests'
    static var allTests: [(String, (RawRepresentableTests) -> () throws -> Void)] {
               ^
SwiftyJSON/Tests/SwiftyJSON/RawRepresentableTests.swift:143:16: note: 'allTests' previously declared here
    static var allTests: [(String, (RawRepresentableTests) -> () throws -> Void)] {
               ^
```

Can you fix this as well?

**Comment by ghost** [comment]
@dfirsht Tests on Linux is still a mess. For example:

``` swift
var jsonTrue:JSON = JSON(rawValue: true as NSNumber)!
XCTAssertEqual(jsonTrue.bool!, true) // failed on Linux, passed on OS X
```

I have not figured out the best way to solve that yet.

**Comment by ghost** [comment]
@dfirsht is there any of my changes helpful at all or they are just duplicated of what you are doing? If not, I don't mind closing the PR.

**Comment by ghost** [comment]
Duplication.

**Pull request closed without merging**
