### PR TITLE
Adapted tests to Swift 3

### PR DESCRIPTION
**Pull request by ghost**
I updated all of the tests to Swift 3 syntax. Even though the framework passes on my local machine, I am unable to figure out what is the best way for CI. Any suggestion is greatly appreciated.

### CODE REVIEW

**Comment by ghost** [comment]
Hello @dfirsht, when you have a chance, can you look at my PR?

**Comment by dfirsht** [comment]
Hey sorry @aquarchitect, we're not used to getting PRs here! What version of the swift toolchain is this updated to? Also for testing, I would just confirm that the tests build and pass both on OSX and Linux.

**Comment by aquarchitect** [comment]
@dfirsht I figured. I know you guys are busy with **Kitura**, so I thought I could help out with the **SwiftyJSON**. This PR was tested successfully against **05.03 Snapshot** on OS X only.

I notice that the framework breaks on OS X with **05.09** but seems working fine on Linux; so I am updating this to **05.09** on Linux (for now). 

Quick question: is this `NSNumber(value: 3) as? Int` possible on Linux?

**Comment by ghost** [comment]
@dfirsht This PR tests successfully against **05/03 Snapshot** on OS X only (I am still having troubles with `NSNumber` on Linux). You run `SwiftyJSON` tests somewhere else also, right?

**Comment by dfirsht** [comment]
Yeah master is in a weird state right now where it compiles on 05/03 on OS X but 05/09 on Linux. We hope to get it compiling on 05/09 on OS X by tomorrow. We don't actually have any CI set up to run tests on SwiftyJSON since any of the changes made is just for migration. However, this latest binary drop introduced some tricky type casting changes that we would really like to be able to test.

If you can get these working on 05/03 on OS X and 05/09 on Linux we'll accept right away.

**Comment by ghost** [comment]
@dfirsht Let's see whether I can make it work. Quick question to confirm: this `NSNumber(value: 3) as? Int` just return `nil` on Linux (05/09), right?

**Comment by dfirsht** [comment]
@aquarchitect Yeah that won't work. You'll need to do `Int(NSNumber(value: 3))`

**Comment by ghost** [comment]
@dfirsht can you close this PR for me? I saw @NikitaSullivan **0509Migration** branch that compiles in OS X; and I will do a PR on that branch instead.

**Comment by dfirsht** [comment]
Alright, sounds good.

**Pull request closed without merging**
